services:
  api_gateway:
    build: ./online-bookstore
    ports:
      - "3000:3000"
    volumes:
      - ./online-bookstore/src:/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  book_microservice:
    build: ./book-service
    volumes:
      - ./book-service/src:/app/src
    command: npm run start:dev
  order_microservice:
    build: ./order-service
    ports:
      - "3001:3001"
    volumes:
      - ./order-service/src:/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
  mysql_db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=online_bookstore
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
